/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Carro;
import model.Data;


/**
 *
 * @author Andriel
 */
public class EstacionamentoEntrada extends javax.swing.JFrame {
    Carro C = new Carro();
    /**
     * Creates new form EstacionamentoEntrada
     */
    public EstacionamentoEntrada() {
        initComponents();
        camposDesabilitadosIni();
        
        setLocationRelativeTo(null);
        //getContentPane().setBackground(Color.BLACK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panelComGuias = new javax.swing.JTabbedPane();
        guiaEntrada = new javax.swing.JPanel();
        panelEntrada = new javax.swing.JPanel();
        txtPlaca = new javax.swing.JLabel();
        inputPlaca = new javax.swing.JTextField();
        txtModelo = new javax.swing.JLabel();
        inputModelo = new javax.swing.JTextField();
        btn_Incluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCarros = new javax.swing.JTable();
        listaCarros = new javax.swing.JLabel();
        guiaSaida = new javax.swing.JPanel();
        panelSaida = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableSaida = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txtPlacaS = new javax.swing.JLabel();
        inputPlacaS = new javax.swing.JTextField();
        txtModeloS = new javax.swing.JLabel();
        InputModeloS = new javax.swing.JTextField();
        btn_sair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));

        panelComGuias.setBackground(new java.awt.Color(254, 254, 254));
        panelComGuias.setForeground(new java.awt.Color(1, 1, 1));
        panelComGuias.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        guiaEntrada.setBackground(new java.awt.Color(113, 113, 113));
        guiaEntrada.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        guiaEntrada.setForeground(new java.awt.Color(1, 1, 1));

        panelEntrada.setBackground(new java.awt.Color(113, 113, 113));
        panelEntrada.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Entrada dos dados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N
        panelEntrada.setForeground(new java.awt.Color(254, 254, 254));

        txtPlaca.setBackground(new java.awt.Color(254, 254, 254));
        txtPlaca.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtPlaca.setText("Placa");
        txtPlaca.setForeground(new java.awt.Color(255, 255, 255));

        txtModelo.setBackground(new java.awt.Color(254, 254, 254));
        txtModelo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtModelo.setText("Modelo");
        txtModelo.setForeground(new java.awt.Color(255, 255, 255));

        btn_Incluir.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_Incluir.setText("Incluir");
        btn_Incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IncluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEntradaLayout = new javax.swing.GroupLayout(panelEntrada);
        panelEntrada.setLayout(panelEntradaLayout);
        panelEntradaLayout.setHorizontalGroup(
            panelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEntradaLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(panelEntradaLayout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(btn_Incluir, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addGap(219, 219, 219))
        );
        panelEntradaLayout.setVerticalGroup(
            panelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEntradaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(inputModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Incluir, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        tableCarros.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tableCarros.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        tableCarros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "Modelo", "Hora entrada", "Data entrada"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableCarros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCarrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableCarros);

        listaCarros.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        listaCarros.setText("Lista de carros no Estacionamento");
        listaCarros.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout guiaEntradaLayout = new javax.swing.GroupLayout(guiaEntrada);
        guiaEntrada.setLayout(guiaEntradaLayout);
        guiaEntradaLayout.setHorizontalGroup(
            guiaEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, guiaEntradaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(listaCarros)
                .addGap(179, 179, 179))
        );
        guiaEntradaLayout.setVerticalGroup(
            guiaEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guiaEntradaLayout.createSequentialGroup()
                .addComponent(panelEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(listaCarros)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1))
        );

        panelComGuias.addTab("Entrada de carro", guiaEntrada);

        guiaSaida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        panelSaida.setBackground(new java.awt.Color(113, 113, 113));

        tableSaida.setBackground(new java.awt.Color(254, 254, 254));
        tableSaida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "Modelo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableSaida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSaidaMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tableSaida);

        jPanel1.setBackground(new java.awt.Color(113, 113, 113));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Saída", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(1, 1, 1));

        txtPlacaS.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtPlacaS.setText("Placa");

        txtModeloS.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtModeloS.setText("Modelo");

        btn_sair.setText("Sair");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtPlacaS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inputPlacaS, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtModeloS)
                        .addGap(18, 18, 18)
                        .addComponent(InputModeloS, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 40, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(btn_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlacaS)
                    .addComponent(inputPlacaS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModeloS)
                    .addComponent(InputModeloS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_sair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        jLabel1.setText("Lista de carros");

        javax.swing.GroupLayout panelSaidaLayout = new javax.swing.GroupLayout(panelSaida);
        panelSaida.setLayout(panelSaidaLayout);
        panelSaidaLayout.setHorizontalGroup(
            panelSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSaidaLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSaidaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(panelSaidaLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel1)
                        .addGap(0, 122, Short.MAX_VALUE))))
        );
        panelSaidaLayout.setVerticalGroup(
            panelSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSaidaLayout.createSequentialGroup()
                .addGroup(panelSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSaidaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelSaidaLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout guiaSaidaLayout = new javax.swing.GroupLayout(guiaSaida);
        guiaSaida.setLayout(guiaSaidaLayout);
        guiaSaidaLayout.setHorizontalGroup(
            guiaSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSaida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        guiaSaidaLayout.setVerticalGroup(
            guiaSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guiaSaidaLayout.createSequentialGroup()
                .addComponent(panelSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelComGuias.addTab("Saída de carro", guiaSaida);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelComGuias)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelComGuias)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_IncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IncluirActionPerformed
        //VERIFICA SE TODOS CAMPOS ESTÃO PREENCHIDOS
        if (inputPlaca.getText().equals("") || inputModelo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Favor preencher todos os campos!");
        } else {
            
            if(verificaCadastrado() == true) {
                Carro carro = new Carro(inputPlaca.getText(), inputModelo.getText());
                C.addLista(carro);

                for(Carro car: C.ListaDeCarros) {
                    System.out.println(car);
                }
            
                loadTableCadastro();
            }
            
        }
        limpaComponentes();
    }//GEN-LAST:event_btn_IncluirActionPerformed

    private void tableCarrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCarrosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableCarrosMouseClicked

    private void tableSaidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSaidaMouseClicked
        int x = tableSaida.getSelectedRow();
        
        InputModeloS.setText(C.ListaDeCarros.get(x).getModelo());
        inputPlacaS.setText(C.ListaDeCarros.get(x).getPlaca());
    }//GEN-LAST:event_tableSaidaMouseClicked
    
    
        public boolean verificaCadastrado() {
        for(Carro car: C.ListaDeCarros) {
                if (car.getPlaca().equals(inputPlaca.getText())) {
                    JOptionPane.showMessageDialog(null, "Este carro com essa placa está no estacionamento!");
                    return false;
                }
            }
            return true;
        }
        
        public void limpaComponentes() {
            inputModelo.setText("");
            inputPlaca.setText("");
        }
    
        public void loadTableCadastro(){
        Data D = new Data();
        DefaultTableModel modelo = (DefaultTableModel) tableCarros.getModel();
        DefaultTableModel modelo2 = (DefaultTableModel) tableSaida.getModel();
        
        
        for(int i = C.ListaDeCarros.size() - 1; i < C.ListaDeCarros.size(); i++) {
            
            modelo.addRow(new Object[]{
                              C.ListaDeCarros.get(i).getPlaca(),
                              C.ListaDeCarros.get(i).getModelo(),
                              D.formataHora(C.ListaDeCarros.get(i).data.getHora()) + ":" +
                              D.formataHora(C.ListaDeCarros.get(i).data.getMinuto()) + ":" +
                              D.formataHora(C.ListaDeCarros.get(i).data.getSegundos()),
                              C.ListaDeCarros.get(i).data.getData()});
            modelo2.addRow(new Object[]{
                              C.ListaDeCarros.get(i).getPlaca(),
                              C.ListaDeCarros.get(i).getModelo()}); 
        }
        //tableCarros.getColumnModel().getColumn(0).setPreferredWidth(200);   REDIMENSIONA TAMANHO DA COLUNA
    }
       public void camposDesabilitadosIni() {
           InputModeloS.setEnabled(false);
       }
       
       
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstacionamentoEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstacionamentoEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstacionamentoEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstacionamentoEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstacionamentoEntrada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InputModeloS;
    private javax.swing.JButton btn_Incluir;
    private javax.swing.JButton btn_sair;
    private javax.swing.JPanel guiaEntrada;
    private javax.swing.JPanel guiaSaida;
    private javax.swing.JTextField inputModelo;
    private javax.swing.JTextField inputPlaca;
    private javax.swing.JTextField inputPlacaS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel listaCarros;
    private javax.swing.JTabbedPane panelComGuias;
    private javax.swing.JPanel panelEntrada;
    private javax.swing.JPanel panelSaida;
    private javax.swing.JTable tableCarros;
    private javax.swing.JTable tableSaida;
    private javax.swing.JLabel txtModelo;
    private javax.swing.JLabel txtModeloS;
    private javax.swing.JLabel txtPlaca;
    private javax.swing.JLabel txtPlacaS;
    // End of variables declaration//GEN-END:variables
}
