
package view;

import Model.Competencia;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelDAO.CompetenciaDAO;

public class PrincipalSistemaFinanceiro extends javax.swing.JFrame {
    Competencia comp = new Competencia();
    ListadeContas LC = new ListadeContas();
    CompetenciaDAO CompDAO = new CompetenciaDAO();
    boolean cadastrado;
    public PrincipalSistemaFinanceiro() throws SQLException {
        initComponents();
        CompDAO.trazDadosDoBancoParaoSistema(comp.ListaCompetencia);
        populaJComboBox(jComboBox1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        TITLE_Cadastro = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        FMT_CompetenciaCadastro = new javax.swing.JFormattedTextField();
        BTN_Cadastrar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        TITLE_Consulta = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BTN_Consultar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jComboBox1 = new javax.swing.JComboBox<>();
        BTN_Excluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setToolTipText("");
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        TITLE_Cadastro.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        TITLE_Cadastro.setText("Cadastro de contas por competência");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Informe a competência:");

        try {
            FMT_CompetenciaCadastro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        FMT_CompetenciaCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FMT_CompetenciaCadastroMouseClicked(evt);
            }
        });
        FMT_CompetenciaCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FMT_CompetenciaCadastroActionPerformed(evt);
            }
        });

        BTN_Cadastrar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BTN_Cadastrar.setText("Cadastrar");
        BTN_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_CadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(TITLE_Cadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(BTN_Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FMT_CompetenciaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TITLE_Cadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FMT_CompetenciaCadastro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTN_Cadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(196, 196, 196))
        );

        jTabbedPane1.addTab("Cadastrar", jPanel1);

        TITLE_Consulta.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        TITLE_Consulta.setText("Consulta/Alteração de contas por competência");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Informe a competência:");

        BTN_Consultar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BTN_Consultar.setText("Consultar");
        BTN_Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ConsultarActionPerformed(evt);
            }
        });

        jComboBox1.setToolTipText("");
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });

        BTN_Excluir.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BTN_Excluir.setText("Excluir");
        BTN_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(TITLE_Consulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(121, 121, 121))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(BTN_Consultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTN_Excluir)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(TITLE_Consulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_Consultar)
                    .addComponent(BTN_Excluir))
                .addContainerGap(184, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Controle", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void verificaCompetenciaCadastrado(){
        for(int i = 0; i < comp.ListaCompetencia.size(); i++){
            if(comp.ListaCompetencia.get(i).getData().equals(FMT_CompetenciaCadastro.getText())){
                cadastrado = true;
                break;
            }else{
                cadastrado = false;
            }
        }
    }
    
    public void ZeraArrayList(){
        for(int i = 0; i < comp.ListaCompetencia.size(); i++){
            comp.ListaCompetencia.remove(i);
        } 
    }
    
    private void BTN_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_CadastrarActionPerformed
        verificaCompetenciaCadastrado();
        if(cadastrado == false){
            ListadeContas L = new ListadeContas();
            L.setVisible(true);
            L.setCompetenciaInicial(FMT_CompetenciaCadastro.getText());
            JOptionPane.showMessageDialog(null,"Iniciando processo de inclusão dos dados da competência...");
        }else{
            JOptionPane.showMessageDialog(null,"Competência já cadastrada, acesse a guia Controle para ter acesso a competências já cadastradas!");
        }

    }//GEN-LAST:event_BTN_CadastrarActionPerformed

    private void BTN_ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_ConsultarActionPerformed

    private void BTN_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_ExcluirActionPerformed

    public void populaJComboBox(javax.swing.JComboBox<String> jComboBox1){
        jComboBox1.removeAllItems();
        for(int i = 0; i < comp.ListaCompetencia.size(); i++){
            jComboBox1.addItem(comp.ListaCompetencia.get(i).getData());
        }
    }

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        ZeraArrayList();
        try {
            CompDAO.trazDadosDoBancoParaoSistema(comp.ListaCompetencia);
        } catch (SQLException ex) {
            System.err.println("Erro ao trazer os dados " + ex);
        }
        populaJComboBox(jComboBox1);
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
       ZeraArrayList();
        try {
            CompDAO.trazDadosDoBancoParaoSistema(comp.ListaCompetencia);
        } catch (SQLException ex) {
            System.err.println("Erro ao trazer os dados " + ex);
        }
        populaJComboBox(jComboBox1);
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void FMT_CompetenciaCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FMT_CompetenciaCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FMT_CompetenciaCadastroActionPerformed

    private void FMT_CompetenciaCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FMT_CompetenciaCadastroMouseClicked
        try {
            CompDAO.trazDadosDoBancoParaoSistema(comp.ListaCompetencia);
        } catch (SQLException ex) {
            System.err.println("Erro ao trazer os dados " + ex);
        }
    }//GEN-LAST:event_FMT_CompetenciaCadastroMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalSistemaFinanceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalSistemaFinanceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalSistemaFinanceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalSistemaFinanceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PrincipalSistemaFinanceiro().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(PrincipalSistemaFinanceiro.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Cadastrar;
    private javax.swing.JButton BTN_Consultar;
    private javax.swing.JButton BTN_Excluir;
    private javax.swing.JFormattedTextField FMT_CompetenciaCadastro;
    private javax.swing.JLabel TITLE_Cadastro;
    private javax.swing.JLabel TITLE_Consulta;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
